SERVER_IP = "127.0.0.1"
DEFAULT_PORT = 1357

PORT_FILE = "myport.info"

VERSION = 2
BUFFER_SIZE = 1024

ID_SIZE = 16
CODE_SIZE = 2
VERSION_SIZE = 1
PAYLOAD_SIZE = 4
REQUEST_HEADER_SIZE = ID_SIZE + CODE_SIZE + VERSION_SIZE + PAYLOAD_SIZE
RESPONSE_HEADER_SIZE = CODE_SIZE + VERSION_SIZE + PAYLOAD_SIZE

NAME_SIZE = 255
PUBLIC_KEY_SIZE = 160

MESSAGE_ID_SIZE = 4
MESSAGE_TYPE_SIZE = 1
SIZE_SIZE = 4
MESSAGE_HEADER = ID_SIZE + MESSAGE_TYPE_SIZE + SIZE_SIZE

RSA_ENCRYPTED_MESSAGE_LENGTH = 128	# 128 bytes = 1024 bits

REGISTER_REQUEST = 600
CLIENTS_LIST_REQUEST = 601
PUBLIC_KEY_REQUEST = 602
SEND_MESSAGE_REQUEST = 603
PENDING_MESSAGES_REQUEST = 604

SUCCESSFUL_REGISTER_RESPONSE = 2100
CLIENTS_LIST_RESPONSE = 2101
PUBLIC_KEY_RESPONSE = 2102
MESSAGE_SENT_RESPONSE = 2103
PENDING_MESSAGES_RESPONSE = 2104
ERROR_RESPONSE = 9000

MESSAGE_TYPE_GET_SYMMETRIC_KEY = 1
MESSAGE_TYPE_SEND_SYMMETRIC_KEY = 2
MESSAGE_TYPE_SEND_MESSAGE = 3
MESSAGE_TYPE_SEND_FILE = 4
